package com.tersesystems.echopraxia.spi;

import com.tersesystems.echopraxia.api.Field;
import com.tersesystems.echopraxia.api.FieldVisitor;
import org.jetbrains.annotations.NotNull;

/**
 * An interface for fields that know about presentation hint attributes.
 *
 * @since 3.0
 */
public interface PresentationHints<F extends Field> {

  /**
   * Tells the formatter that the field should be rendered with the value only, i.e. "value" and not
   * "name=value".
   *
   * @return valueOnly field
   */
  @NotNull
  F asValueOnly();

  /**
   * Tells the formatter that the array value should be represented as a cardinal number in text.
   *
   * @return field with cardinal attribute set
   * @deprecated asCardinal attribute only applies to values, this will not set an attribute on the field.
   */
  @Deprecated
  @NotNull
  F asCardinal();

  /**
   * Tells the formatter that the string value or array value should be abbreviated after the given
   * number of elements.
   *
   * @deprecated abbreviateAfter attribute only applies to values, this will not set an attribute on the field.
   *
   * @param after the maximum number of elements to render
   * @return the field with the attribute applied
   */
  @Deprecated
  @NotNull
  F abbreviateAfter(int after);

  /**
   * Tells the formatter that this field should be elided in text.
   *
   * @return field with elide attribute set
   */
  @NotNull
  F asElided();

  /**
   * Tells the formatter to render a display name in text.
   *
   * @return the field with displayName set
   */
  @NotNull
  F withDisplayName(@NotNull String displayName);

  /**
   * Tells the structured output to use the output generated by the field visitor.
   *
   * @param fieldVisitor the visitor generating the JSON specific output.
   * @return the field with the visitor set
   */
  @NotNull
  F withStructuredFormat(@NotNull FieldVisitor fieldVisitor);

  /**
   * Tells the ToStringFormatter to use the output generated by the field visitor.
   *
   * @param fieldVisitor the visitor generating the toString specific output.
   * @return the field with the visitor set
   */
  @NotNull
  F withToStringFormat(@NotNull FieldVisitor fieldVisitor);
}
