package com.tersesystems.echopraxia.spi;

import com.tersesystems.echopraxia.api.Field;
import com.tersesystems.echopraxia.api.FieldVisitor;
import org.jetbrains.annotations.NotNull;

/**
 * An interface for fields that know about presentation hint attributes.
 *
 * @since 3.0
 */
public interface PresentationHints<F extends Field> {

  /**
   * Tells the formatter that the field should be rendered with the value only, i.e. "value" and not
   * "name=value".
   *
   * @return valueOnly field
   */
  @NotNull
  F asValueOnly();

  /**
   * Tells the formatter that this field should be elided in text.
   *
   * @return field with elide attribute set
   */
  @NotNull
  F asElided();

  /**
   * Tells the formatter to render a display name in text.
   *
   * @return the field with displayName set
   */
  @NotNull
  F withDisplayName(@NotNull String displayName);

  /**
   * Tells the structured output to use the output generated by the field visitor.
   *
   * @param fieldVisitor the visitor generating the JSON specific output.
   * @return the field with the visitor set
   */
  @NotNull
  F withStructuredFormat(@NotNull FieldVisitor fieldVisitor);

  /**
   * Tells the ToStringFormatter to use the output generated by the field visitor.
   *
   * @param fieldVisitor the visitor generating the toString specific output.
   * @return the field with the visitor set
   */
  @NotNull
  F withToStringFormat(@NotNull FieldVisitor fieldVisitor);
}
